### ISSUE TITLE
Wireguard VPN setup but Engarde doesn't connect to server

### ISSUE THREAD

**Issue by regstuff** [porech/engarde#41]
I'm trying to connect from a Windows 10 client to a Ubuntu 18.04 server in the cloud.

Wireguard is all set up and working fine. Able to ping from client to server and server to client. Using it to browse etc.

But once I get Engarde running, nothing seems to be working. I'm unable to ping server from client or ping client from server. Strangely, I'm able to ping 1.1.1.1 from the client but something seems odd as the rtt is 9ms. I usually get around 40 ms.

Came across [this issue](https://github.com/porech/engarde/issues/37#issuecomment-647745330) about Allowed IPs set to 0.0.0.0 possibly causing an issue, but I can't figure out what to change there.

Also came across [your discussion](https://lists.zx2c4.com/pipermail/wireguard/2020-April/005325.html) on Wireguard mailing lists about an issue with 127.0.0.1 in the Wireguard Windows client. Again, not sure what I can do to fix it. 

I'm not much of a network guy so please make the explanation simple. :)

Thanks again for all your effort.

Below are my wireguard configs & then engarde.yml.

```
Wireguard Server config:

[Interface]
Address = 192.168.2.1
PrivateKey = ******
ListenPort = 54320
SaveConfig = false
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens4 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens4 -j MASQUERADE

[Peer]
PublicKey = *****
AllowedIPs = 192.168.2.2/24
```

Wireguard Client config:

[Interface]
PrivateKey = ****
Address = 192.168.2.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = *****
AllowedIPs = 0.0.0.0/0
Endpoint = 127.0.0.1:54320

Engarde config
```
---
# Client configuration
client:
  description: "My engarde-client instance"
  listenAddr: "127.0.0.1:54320"
  dstAddr: "SERVERIP:54321"
  writeTimeout: 10
  excludedInterfaces:
    - "Local Area Connection 1"
    - "Local Area Connection 2"
    - "GCPMumbai"
    - "Bluetooth Network Connection"
    - "Loopback Pseudo-Interface 1"
  dstOverrides: []
  
  webManager:
    listenAddr: "0.0.0.0:9001"
    username: "engarde"
    password: "engarde"

# Server configuration
server:
  description: "My engarde-server instance"
  listenAddr: "0.0.0.0:54321"
  dstAddr: "127.0.0.1:54320"
  clientTimeout: 30
  writeTimeout: 10
  webManager:
    listenAddr: "0.0.0.0:80"
    username: "engarde"
    password: "engarde"
```
